name: Continuous Integration
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: olafurpg/setup-scala@v13
        with:
          distribution: temurin
          java-version: openjdk@1.17
      - name: Unit Tests
        run: sbt +test